# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoginDN' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoginDN

  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  
  # Pods for LoginSocial
  pod 'FBSDKLoginKit'
 
  pod 'TextFieldEffects'
  pod 'lottie-ios'
  
  pod 'Alamofire'
  pod 'SDWebImage'
end
